export const outubroRosaSante = {
  id: "sante-outubro-rosa-2026",
  client: "Santé Laboratório Veterinário",
  format: { width: 1080, height: 1350, ratio: "4:5" },
  footer: "Gláucia Dias · CRMV-DF 1042",
  requirements: {
    slides: 6,
    tone: "afetivo",
    light: "quente",
    pinkRibbon: "discreto",
    forbiddenImagery: ["lesão", "tumor", "animal doente"],
    preserveTechnicalContext: true,
  },
  slides: [
    {
      index: 1,
      role: "cover",
      title: "OUTUBRO ROSA TAMBÉM É DELAS.",
      body: "O carinho de todo dia pode achar um carocinho antes de qualquer exame.",
      visual: "Tutora fazendo carinho na barriga de uma cadela ou gata deitada.",
    },
    {
      index: 2,
      role: "education",
      title: "Elas também têm mama.",
      body: "São duas fileiras, da axila até a virilha. É ali que costuma aparecer o primeiro sinal.",
      visual: "Ilustração suave da cadeia mamária em linha.",
    },
    {
      index: 3,
      role: "education",
      title: "O CARINHO QUE VIRA CHECK-UP.",
      body: "Passe a mão aberta nas duas fileiras, de cima até embaixo, sem apertar. Você está sentindo se apareceu algum carocinho novo.",
      visual: "Mão passando carinho na barriga do animal.",
    },
    {
      index: 4,
      role: "habit",
      title: "Uma vez por mês já basta.",
      body: "Escolha um dia fácil de lembrar. O carinho já acontece todo dia mesmo.",
      visual: "Calendário simples com um coração marcado.",
    },
    {
      index: 5,
      role: "prevention",
      title: "Castrar cedo ajuda a proteger.",
      body: "E tem uma coisa que reduz bastante o risco lá na frente: castrar cedo. Converse com o veterinário sobre o melhor momento.",
      visual: "Cadela ou gata jovem deitada ao sol, luz suave.",
    },
    {
      index: 6,
      role: "cta",
      title: "Achou um carocinho?",
      body: "Não espere pra ver se cresce. Leve ao veterinário. Quanto mais cedo, mais simples costuma ser o caminho.",
      cta: "Manda esse post pra quem tem uma menina de quatro patas em casa.",
      visual: "Fundo claro, laço rosa em linha fina.",
    },
  ],
} as const;
